Meeting 2023-12-07 minutes
oasis-tcs/sarif-spec pull request #616
Opened 2023-12-07 03:36 UTC by sthagen

- [x] pre-meeting minutes draft
- [x] post-meeting revision (ready for review)

2023-12-08 16:42 UTC, katrinaoneil approved these changes

2023-12-08 22:56 UTC, stacywray commented on meeting_minutes/231207_SARIF_TC_82.md
> +   * at the January, 11 meeting the TC has the reference representation of v2.1 Errata 01 to approve it
- Add comma after "meeting"
- Add "ready" before "to approve"

2023-12-08 22:57 UTC, stacywray commented on meeting_minutes/231207_SARIF_TC_82.md
> +   * then, by the February, 8 meeting to have approved proposals to merge into the v2.2 working draft
- Add comma after "meeting"
- Add "ready" before "to merge"
- Add period at end of sentence.

2023-12-08 22:58 UTC, stacywray commented on meeting_minutes/231207_SARIF_TC_82.md
> + * Michael: Hopes to have by end of June 2024 have the bulk of small changes for v2.2 merged into and then only have to polish for progressing the v2.2 towards OASIS Standard
- Remove the second instance of "have"
- Remove "into"
- Add period at end of sentence

2023-12-08 23:00 UTC, stacywray commented on meeting_minutes/231207_SARIF_TC_82.md
> +   * Suggests to continue with adding more examples and then have this proposal one of the first additions (v2.2)
- Add "be" after "this proposal"
- Add period at the end of sentence

2023-12-08 23:00 UTC, stacywray commented on meeting_minutes/231207_SARIF_TC_82.md
> +   * Points everyone to [OS SARIF v2.1.0 section 3.9 "Date/time properties"](https://docs.oasis-open.org/sarif/sarif/v2.1.0/errata01/os/sarif-v2.1.0-errata01-os-complete.html#_Toc141790703)
Add period at the end.

2023-12-08 23:02 UTC, stacywray commented on meeting_minutes/231207_SARIF_TC_82.md
> + * Charles: Encourages to bring examples also for expanded ISO8601 forms
Rewrite to: "Encourages author to add examples for expanded ISO8601 forms."

2023-12-08 23:03 UTC, stacywray commented on meeting_minutes/231207_SARIF_TC_82.md
> + * Michael: Shows everyone some examples of how similar the html/pdf paragraphs look like the issue text rendered in GitHub
- Add "when" after "like"
- Add "is" before "rendered"
- Add period at the end

2023-12-08 23:04 UTC, stacywray commented on meeting_minutes/231207_SARIF_TC_82.md
> +* DECISION to approve the issue [Suggestion: add an expiryDateUtc property to suppression instances #492](https://github.com/oasis-tcs/sarif-spec/issues/492) as discussed implementing the comment of
Add period to end.

2023-12-08 23:04 UTC, stacywray commented on meeting_minutes/231207_SARIF_TC_82.md
> +  [Future.md](https://github.com/oasis-tcs/sarif-spec/blob/main/Future.md) per pull request
Add period to end.

2023-12-08 23:05 UTC, stacywray commented on meeting_minutes/231207_SARIF_TC_82.md
> +* ACTION on Michael to triage on issue
- Remove "on"
- Add period at end

2023-12-08 23:05 UTC, stacywray commented on meeting_minutes/231207_SARIF_TC_82.md
> +* ACTION on Michael to organize label renovation
Add period to end.

2023-12-08 23:07 UTC, stacywray requested changes
Minor edits and punctuation. Thanks!

2023-12-09 22:10 UTC, sthagen commented
@stacywray I do not put full stops at the end of list items. Thanks for the corrections. Besides the action on Michael no semantics did change. The action was to triage old issues not all issues (that is what I remember).

2023-12-11 16:07 UTC, stacywray approved these changes

2023-12-18 21:19 UTC, merged