Meeting 2024-01-11 minutes draft
oasis-tcs/sarif-spec pull request #620
Opened 2024-01-10 21:25 UTC by sthagen

- [x] pre meeting draft
- [ ] post meeting draft

2024-01-10 21:38 UTC, stacywray approved these changes

2024-01-11 17:24 UTC, stacywray commented on meeting_minutes/240111_SARIF_TC_83.md
> + * Aditiya: On precision and severity topic two changes require further detailing which he will do together with Micahel before the next meeting
correct Michael spelling

2024-01-11 17:24 UTC, stacywray commented on meeting_minutes/240111_SARIF_TC_83.md
> +* All reviwe the pull request [futures addition #621](https://github.com/oasis-tcs/sarif-spec/pull/621)
Correct "review" spelling

2024-01-11 17:25 UTC, stacywray commented on meeting_minutes/240111_SARIF_TC_83.md
> +    * enlarge reagions which are of interest only to some use cases and would
Correct "regions" spelling

2024-01-11 17:27 UTC, stacywray commented on meeting_minutes/240111_SARIF_TC_83.md
> +* ACTION on Davoid Malcolm to create a first link list for SARIF producers and consumers (from the wikipedia article draft on SARIF)
Correct "David" spelling

2024-01-11 17:28 UTC, stacywray commented on meeting_minutes/240111_SARIF_TC_83.md
> +* ACTION on Charles to start the list of links to SARIF related activities on the TC repo wiki
Add "hyphen" between "SARIF" "related"

2024-01-11 17:29 UTC, stacywray requested changes
Commented on minor spelling errors.

2024-02-03 03:19 UTC, dmk42 approved these changes
Thanks!

2024-02-03 08:32 UTC, merged